# This is a basic workflow to help you get started with Actions

name: lamp

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    job1:
      build:
        runs-on: ubuntu-latest
        steps:
          - name: stepOne
            uses: actions/checkout@v4
          - name: stepTwo
            run:  env | sort
    job2:
      build:
        runs-on: windows-latest
        steps:
          - name: stepOne
            uses: actions/checkout@v4
          - name: stepTwo
            run:  "Get-childitem Env: | Sort-Object Name"


